name: Build test images
on: push
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                version:
                    - "6.1.0.1418"
                    - "6.1.1.1420"
                    - "6.1.2.1421"
                    - "6.1.3.1424"
                    - "6.1.4.1429"
                    - "6.1.5.1433"
                    - "6.1.6.1439"
                    - "7.2.0.2013"
                    - "7.3.0.2018"
                    - "7.3.1.2022"
                    - "7.4.0.2026"
                    - "7.4.1.2028"
                    - "7.4.2.2033"
                    - "7.4.3.2036"
                    - "7.4.4.2039"
                    - "7.4.5.2041"
                    - "7.4.6.2043"
                    - "7.4.7.2045"
                    - "7.4.8.2046"
                    - "7.4.9.2047"
                    - "7.4.10.2049"
                    - "8.0.0.3020"
                    - "8.1.0.3027"
                    - "8.1.1.3029"
                    - "8.1.2.3031"
                    - "8.1.3.3033"
                    - "8.1.4.3035"
                    - "8.2.0.3103"
                    - "8.2.1.3105"
                    - "8.2.2.3107"
                    - "8.2.3.3109"
                    - "8.3.1.3205"
                    - "8.3.2.3207"
                    - "8.3.3.3209"
                    - "8.4.0.3402"
                    - "2019.03.3412"
                    # - "2019.03.2.3414"  # Servoy's link for this one doesn't work
                    # - "2019.06.3502"    # Servoy doesn't have a link for this one
                    - "2019.06.1.3503"
                    - "2019.06.2.3504"
                    - "2019.09.3522"
                    - "2019.12.3542"
                    - "2019.12.1.3543"
                    - "2020.03.3562"
                    - "2020.03.1.3563"
                    - "2020.03.2.3564"
                    - "2020.03.3.3565"
                    - "2020.06.3582"
                    - "2020.06.1.3583"
                    - "2020.09.3602"
                    - "2020.12.3622"
                    - "2020.12.1.3623"
                    - "2021.03.3642"
                    - "2021.03.1.3643"
                    - "2021.03.2.3644"
                    - "2021.03.3.3645"
                    - "2021.06.3683"
                    - "2021.09.3703"
                    - "2021.12.3722"
                    - "2021.12.1.3723"
                    - "2021.12.2.3724"
                    - "2022.03.3742"
                    - "2022.03.1.3743"
                    - "2022.03.2.3744"
                    - "2022.03.3.3745"
                    - "2022.03.4.3746"
                    - "2022.03.5.3747"
                    - "2022.03.6.3748"
                    - "2022.03.7.3749"
                    - "2022.03.8.3750"
                    - "2022.03.9.3751"
                    - "2022.03.10.3752"
                    - "2022.06.3782"
                    - "2022.09.3803"
                    - "2022.09.1.3804"
                    - "2022.09.2.3805"
                    - "2022.12.0.3823"
                    - "2022.12.1.3824"
                    - "2023.03.3842"
                    - "2023.03.1.3843"
                    - "2023.03.2.3844"
                    - "2023.03.3.3845"
                    - "2023.03.4.3846"
                    - "2023.03.5.3847"
                    - "2023.03.6.3848"
                    - "2023.03.7.3849"
                    - "2023.03.8.3850"
                    - "2023.03.9.3851"
                    - "2023.06.3883"
                    - "2023.09.3902"
                    - "2023.09.1.3903"
                    - "2023.12.3922"
                    - "2023.12.1.3923"
                    - "2023.12.2.3924"
                    - "2024.03.3943"
                    - "2024.03.1.3944"
                    - "2024.03.2.3945"
                    - "2024.03.3.3946"
                    - "2024.03.4.3947"
                    - "2024.03.5.3948"
                    - "2024.03.6.3949"
                    - "2024.03.7.3950"
                    - "2024.03.8.3951"
                    - "2024.03.9.3952"
                    - "2024.06.3982"
                    - "2024.06.1.3983"
                    - "2024.09.4002"
                    - "2024.09.1.4003"
                    - "2024.12.4023"
                    - "2025.03.4042"
                    - "2025.03.1.4043"
                    - "2025.03.2.4044"
                    - "2025.03.3.4045"
                    - "2025.03.4.4046"
                    - "2025.06.4082"
                    - "2025.06.1.4083"
                    - "2025.06.2.4084"
                    - "2025.09.4102"
                    - "2025.09.1.4103"
                    - "2025.12.4122"
                    - "2025.12.1.4123"
                    - "nightly"
                    - "nightly-lts"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Servoy test image
              run: |
                docker build -t ServoyComponents/servoy_tester:${{matrix.version}} --build-arg DEVELOPER_VERSION_BUILD=${{matrix.version}} developer-tester
            - name: Push Servoy test image
              run: |
                docker push ServoyComponents/servoy_tester:${{matrix.version}}
